[package]
name = "keystone-cc-scenes"
version = "0.1.0"
edition = "2021"

[dependencies]
keystone-cc-core = { path = "../core" }
keystone-cc-adapter = { path = "../adapter" }
bevy = { workspace = true }
